use Mojo::Base -strict;

use Test::Mojo;
use Test::More;
use Test::Files;
use Mojo::File qw(path);

diag "need some files to test...";
my $fh = undef;
my $testdir = path('/tmp', 'r2d2test')->make_path;
while (<DATA>) {
  last if /^__END__$/;
  if (/^@@ *(\S+)$/) {
    diag "prepare file $1";
    $fh->close if $fh;
    $fh = path($testdir, $1)->open('>');
    next;
  }
  print $fh $_ if $fh;
}
$fh->close if $fh;


# my $t = $make_test->($test_mojo_file);
my $make_test = sub {
  my $tf = shift;
  return Test::Mojo->new('Rtsyn', { firewall_file => $tf->to_string,
    rlog_local=>1, rlog_remote=>0,
    my_profiles=>['plk'],
  });
};

note "common usage";
my $test_f = path($testdir, 'firewall-rtsyn.clients1');
my $t = $make_test->($test_f);
is($t->app->rt_delete(451), 1, 'rt_delete1 451');
is($t->app->rt_delete(452), 1, 'rt_delete1 452');
is($t->app->rt_delete(452), 0, 'rt_delete1 452 non existent');
is($t->app->rt_delete(450), 1, 'rt_delete1 450');
compare_ok($test_f, path($testdir, 'result1'), 'compare results 1');
undef $t;

note "with newlines";
$test_f = path($testdir, 'firewall-rtsyn.clients2');
$t = $make_test->($test_f);
is($t->app->rt_delete(450), 1, 'rt_delete2 450');
compare_ok($test_f, path($testdir, 'result2'), 'compare results 2');
undef $t;

note "without rules";
$test_f = path($testdir, 'firewall-rtsyn.clients3');
$t = $make_test->($test_f);
is($t->app->rt_delete(452), 1, 'rt_delete3 452');
compare_ok($test_f, path($testdir, 'result3'), 'compare results 3');
undef $t;

note "without all rules";
$test_f = path($testdir, 'firewall-rtsyn.clients4');
$t = $make_test->($test_f);
is($t->app->rt_delete(450), 0, 'rt_delete4 450');
compare_ok($test_f, path($testdir, 'result4'), 'compare results 4');
undef $t;

note "intersecting ids: 45 and 450";
$test_f = path($testdir, 'firewall-rtsyn.clients5');
$t = $make_test->($test_f);
is($t->app->rt_delete(45), 0, 'rt_delete5 45 non existent');
is($t->app->rt_delete(450), 1, 'rt_delete5 450');
compare_ok($test_f, path($testdir, 'result5'), 'compare results 5');
undef $t;

note "duplicate ids, issue warnings";
$test_f = path($testdir, 'firewall-rtsyn.clients6');
$t = $make_test->($test_f);
is($t->app->rt_delete(450), 1, 'rt_delete6 450 duplicate ids, issue warnings');
compare_ok($test_f, path($testdir, 'result6'), 'compare results 6');
undef $t;

done_testing();

__DATA__
@@ firewall-rtsyn.clients1
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
-A pipe_out_inet_clients -s 192.168.34.23 -m comment --comment 450
-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 451 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
@@ result1
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
COMMIT
@@ firewall-rtsyn.clients2
# WARNING: this is autogenerated file, don't run or change it!
*mangle

-A pipe_out_inet_clients -s 192.168.34.23 -m comment --comment 450

-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 451 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452
COMMIT
@@ result2
# WARNING: this is autogenerated file, don't run or change it!
*mangle


-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 451 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452
COMMIT
@@ firewall-rtsyn.clients3
# WARNING: this is autogenerated file, don't run or change it!
*mangle
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
@@ result3
# WARNING: this is autogenerated file, don't run or change it!
*mangle
COMMIT
@@ firewall-rtsyn.clients4
# WARNING: this is autogenerated file, don't run or change it!
*mangle
@@ result4
# WARNING: this is autogenerated file, don't run or change it!
*mangle
@@ firewall-rtsyn.clients5
# WARNING: this is autogenerated file, don't run or change it!
*mangle
-A pipe_in_inet_clients -d 192.168.34.23 -m comment --comment 450
-A pipe_in_inet_clients -d 192.168.34.23 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
@@ result5
# WARNING: this is autogenerated file, don't run or change it!
*mangle
-A pipe_in_inet_clients -d 192.168.34.23 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
@@ firewall-rtsyn.clients6
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]

-A pipe_out_inet_clients -s 192.168.34.23 -m comment --comment 450
-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 450 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.26 -m comment --comment 450
COMMIT
@@ result6
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]

-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
__END__
