use Mojo::Base -strict;

use Test::Mojo;
use Test::More;
use lib '../ljq/lib';
use Test::Files;
use Mojo::File qw(path);

diag "need some files to test...";
my $fh = undef;
my $testdir = path('/tmp', 'r2d2test')->make_path;
while (<DATA>) {
  last if /^__END__$/;
  if (/^@@ *(\S+)$/) {
    diag "prepare file $1";
    $fh->close if $fh;
    $fh = path($testdir, $1)->open('>');
    next;
  }
  print $fh $_ if $fh;
}
$fh->close if $fh;


# my $t = $make_test->($test_mojo_file);
my $make_test = sub {
  my $tf = shift;
  return Test::Mojo->new('Rtsyn', { firewall_file => $tf->to_string,
    client_out_chain=>'pipe_out_inet_clients',
    rlog_local=>1, rlog_remote=>0,
    my_profiles=>['plk'],
    worker_db_file=>'/tmp/test$$.dat',
  });
};

note "common usage";
my $test_f = path($testdir, 'firewall-rtsyn.clients1');
my $t = $make_test->($test_f);
is($t->app->rt_add_replace({id=>451,ip=>'1.2.4.51',rt=>0}), 1, 'rt_add_replace1 451 replaced');
is($t->app->rt_add_replace({id=>450,ip=>'1.2.4.50',rt=>1}), 1, 'rt_add_replace1 450 replaced');
is($t->app->rt_add_replace({id=>452,ip=>'1.2.4.52',rt=>0}), 1, 'rt_add_replace1 452 replaced');
is($t->app->rt_add_replace({id=>10,ip=>'1.2.3.10',rt=>1}), 1, 'rt_add_replace1 10 added');
compare_ok($test_f, path($testdir, 'result1'), 'compare results 1');
undef $t;

note "bad format";
$test_f = path($testdir, 'firewall-rtsyn.clients2');
$t = $make_test->($test_f);
is($t->app->rt_add_replace({id=>1,ip=>'1.2.3.1',rt=>1}), 1, 'rt_add_replace2 1 added');
is($t->app->rt_add_replace({id=>2,ip=>'1.2.3.2',rt=>0}), 1, 'rt_add_replace2 2 added');
compare_ok($test_f, path($testdir, 'result2'), 'compare results 2');
undef $t;

note "regex intersections and formats";
$test_f = path($testdir, 'firewall-rtsyn.clients3');
$t = $make_test->($test_f);
is($t->app->rt_add_replace({id=>10,ip=>'1.2.3.10',rt=>0}), 1, 'rt_add_replace3 10 added');
is($t->app->rt_add_replace({id=>2,ip=>'1.2.3.2',rt=>1}), 1, 'rt_add_replace3 2 added');
is($t->app->rt_add_replace({id=>1,ip=>'1.2.3.1',rt=>0}), 1, 'rt_add_replace3 1 added');
compare_ok($test_f, path($testdir, 'result3'), 'compare results 3');
undef $t;

note "duplicate ids, issue warnings";
$test_f = path($testdir, 'firewall-rtsyn.clients4');
$t = $make_test->($test_f);
is($t->app->rt_add_replace({id=>450,ip=>'192.168.34.45',rt=>1}), 1, 'rt_add_replace4 450 replaced, duplicate ids removed, warnings issued');
compare_ok($test_f, path($testdir, 'result4'), 'compare results 4');
undef $t;

done_testing();

__DATA__
@@ firewall-rtsyn.clients1
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
-A pipe_out_inet_clients -s 192.168.34.23 -m comment --comment 450 
-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 451 
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452 -j MARK --set-mark 2
COMMIT
@@ result1
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
-A pipe_out_inet_clients -s 1.2.4.50 -m comment --comment 450 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 1.2.4.51 -m comment --comment 451 
-A pipe_out_inet_clients -s 1.2.4.52 -m comment --comment 452 
-A pipe_out_inet_clients -s 1.2.3.10 -m comment --comment 10 -j MARK --set-mark 2
COMMIT
@@ firewall-rtsyn.clients2
@@ result2
-A pipe_out_inet_clients -s 1.2.3.1 -m comment --comment 1 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 1.2.3.2 -m comment --comment 2 
COMMIT
@@ firewall-rtsyn.clients3
# WARNING: this is autogenerated file, don't run or change it!

*mangle
@@ result3
# WARNING: this is autogenerated file, don't run or change it!

*mangle
-A pipe_out_inet_clients -s 1.2.3.10 -m comment --comment 10 
-A pipe_out_inet_clients -s 1.2.3.2 -m comment --comment 2 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 1.2.3.1 -m comment --comment 1 
COMMIT
@@ firewall-rtsyn.clients4
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
-A pipe_out_inet_clients -s 192.168.34.23 -m comment --comment 450
-A pipe_out_inet_clients -s 192.168.34.24 -m comment --comment 450
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452
COMMIT
@@ result4
# WARNING: this is autogenerated file, don't run or change it!

*mangle
:pipe_out_inet_clients - [0:0]
-A pipe_out_inet_clients -s 192.168.34.45 -m comment --comment 450 -j MARK --set-mark 2
-A pipe_out_inet_clients -s 192.168.34.25 -m comment --comment 452
COMMIT
__END__
