openapi: 3.0.0
info:
  version: '3.00'
  title: Agent api
  description: 'API модуля agent'
paths:
  /subsys:
    get:
      summary: Имя модуля агента и версия
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
                example: 'rtsyn@wispa (3.00)'
            application/json:
              schema:
                type: object
                properties:
                  subsys:
                    type: string
                    example: 'rtsyn@wispa'
                  version:
                    type: string
                    example: '3.00'
                  profiles:
                    type: array
                    items:
                      type: string
                      example: 'gwtest1'

  /refresh/{id}:
    post:
      summary: Refresh client
      parameters: 
        - name: id
          in: path
          required: true
          description: client id
          schema:
            type: integer
            example: 11
            
      responses:
        '200':
          description: Successfully queued
        '503':
          description: Bad id, connection problems, etc
          content:
            text/plain:
              schema:
                type: string
                description: error message

  /runstat:
    post:
      summary: Request traffic statistic collection
      responses:
        '200':
          description: Successfully queued
        '501':
          description: Not implemented. Agent doesn't support statistics collection.
        '503':
          description: Task run problems
          content:
            text/plain:
              schema:
                type: string
                description: error message

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/uralm1/agent/3.00