#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=02

start_service() {
  procd_open_instance
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param command /etc/r2d2/script/fwsyn ljq worker
  procd_close_instance
}
