#!/bin/sh

echo "* Generating new makefiles"
for d in ljq dhcpsyn fwsyn gwsyn head rtsyn ui; do
  echo "** Operating on $d"
  cd $d
  perl Makefile.PL
  cd ..
  echo ""
done
echo "* Operation finished"
