#!/bin/sh /etc/rc.common
USE_PROCD=1
START=98
STOP=01

start_service() {
  sp=`/usr/bin/perl -MMojolicious::Plugin::Config -E 'my $c=Mojolicious::Plugin::Config->new->load("/etc/r2d2/gwsyn.conf");say "?cert=$c->{local_cert}&key=$c->{local_key}&ca=$c->{ca}&verify=0x03"'`

  procd_open_instance
  procd_set_param env MOJO_LISTEN="https://*:2275$sp"
  procd_set_param stdout 1
  procd_set_param stderr 1
  #procd_set_param command /etc/r2d2/script/gwsyn prefork -w 2 -P /tmp/gwsyn-prefork.pid
  procd_set_param command /etc/r2d2/script/gwsyn daemon
  procd_close_instance
}
