#!/bin/sh

ip1=beko.uwc.local

echo "System startup precheck"
echo "Waiting for $ip1 goes online..."
for cc in `seq 90`
do
  if ping -c 1 $ip1 &>/dev/null
  then
    break
  fi
  #echo -n "$cc "
  sleep 2
done

[ -e /opt/master/run/master.pid ] && { echo "Removing stalled master.pid file."; rm -f /opt/master/run/master.pid; }

echo "All OK"
