#!/bin/sh

#make dist
version=`perl -E 'use lib "lib";use Rtsyn;say $Rtsyn::VERSION'`
version_ljq=`perl -E 'use lib "../ljq/lib";use Ljq;say $Ljq::VERSION'`

rexlib=root@bikini:/var/www/net/rexlib
destdir=$rexlib/lib/Deploy/Erebus/R2d2/files

# check files
[ ! -f ../ljq/ljq-$version_ljq.tar.gz ] && echo "ERROR: ljq source tarball is not found! Run make dist first." && exit 1
[ ! -f rtsyn-$version.tar.gz ] && echo "ERROR: rtsyn source tarball is not found! Run make dist first." && exit 1

# source tarballs
cp rtsyn-$version.tar.gz rtsyn-latest.tar.gz
cp ../ljq/ljq-$version_ljq.tar.gz ljq-latest.tar.gz
filelist="rtsyn-latest.tar.gz ljq-latest.tar.gz"

# copy keys
cert_path="../cert"
keys="$cert_path/ca.pem"
for h in erebus
do
  keys="$keys $cert_path/$h-cert.pem $cert_path/$h-key.pem"
done
#echo $keys
filelist="$filelist $keys"

# service scripts
filelist="$filelist support/rtsyn support/rtsyn-worker"

scp $filelist $destdir

rm rtsyn-latest.tar.gz ljq-latest.tar.gz
