requires 'EV';
requires 'Mojolicious', '8.09';
requires 'Cpanel::JSON::XS', '4.10';

on 'configure' => sub {
  requires 'Module::Build';
  requires 'Module::CPANfile';
};

on 'test' => sub {
#  requires 'Test::More';
};
