requires 'Mojolicious', '8.50';
requires 'EV';
requires 'Cpanel::JSON::XS', '4.10';
requires 'IO::Socket::SSL', '2.009';
requires 'Minion', '10.03';
requires 'Minion::Backend::SQLite';

on 'configure' => sub {
  requires 'Module::Build';
  requires 'Module::CPANfile';
};

on 'test' => sub {
#  requires 'Test::More';
};
