#!/usr/bin/perl

# for test
#iptables -t mangle -N testchain
#iptables -t mangle -A testchain -s 1.2.3.4 -p tcp -j ACCEPT
#iptables -t mangle -A testchain -d 1.2.3.4 -j MARK --set-mark 4
#iptables -t mangle -X testchain

use IPTables::IPv4;
use warnings;

my $table = IPTables::IPv4::init('mangle');

#@chains = $table->list_chains();
#foreach (@chains) {
#  print $_,"\n";
#}

$table->is_chain('testchain') or die "Add testchain!";

my @rules = $table->list_rules('testchain');
foreach $rhashref (@rules) {
  my @rh = %{$rhashref};
  print "@rh\n\n";
}

print "-------------------------------\n";
my @aa = @{${$rules[2]}{'matches'}};
print "@aa\n";

print "-------------------------------\n";
my %h1 = (
  'destination' => '3.4.5.6',
#  'jump' => 'MARK',
#  'set-mark' => '4',
);

my %h2 = (
  'source' => '2.3.4.5',
  'matches' => ['mac'],
  'mac-source' => '22:22:22:22:22:22',
  'jump' => 'ACCEPT',
);

  my @z = %{\%h2};
  print "@z\n\n";
 @aa = @{$h2{'matches'}};
print "@aa\n";
#$table->append_entry('testchain', \%h1) or die;
#$table->replace_entry('testchain', \%h1, 3) or die;
#$table->commit or die;
