#!/bin/bash

# verify = SSL_VERIFY_PEER (0x01) & SSL_VERIFY_FAIL_IF_NO_PEER_CERT (0x02)
SP=`perl -MMojolicious::Plugin::Config -E 'my $c=Mojolicious::Plugin::Config->new->load("head.conf");say "?cert=$c->{local_cert}&key=$c->{local_key}&ca=$c->{ca}&verify=0x03"'`

#MOJO_LISTEN="https://*:2271$SP"
MOJO_LISTEN='http://*:2271'

#echo $MOJO_LISTEN
export MOJO_LISTEN

morbo script/head
#script/head daemon
#script/head prefork
