#!/bin/bash

docker run -d --name r2d2-head-cron \
  -v /srv/r2d2/head.conf:/opt/head/head.conf:ro \
  -v /srv/r2d2/r2d2-head-cert.pem:/opt/head/r2d2-head-cert.pem:ro \
  -v /srv/r2d2/r2d2-head-key.pem:/opt/head/r2d2-head-key.pem:ro \
  -v /srv/r2d2/ca.pem:/opt/head/ca.pem:ro \
  -e TZ=Asia/Yekaterinburg \
  --cap-add NET_ADMIN \
  uralm1/r2d2-head sh -c "script/check_db_hosts && script/add_route && script/head cron"
