requires 'Mojolicious', '8.50';
requires 'EV';
requires 'Cpanel::JSON::XS', '4.10';
requires 'IO::Socket::SSL', '2.009';
requires 'Mojo::mysql', '1.04';
requires 'Algorithm::Cron', '0.10';
requires 'NetAddr::IP';
requires 'Net::SMTP';
requires 'ExtUtils::MakeMaker::CPANfile';

on 'configure' => sub {
  requires 'ExtUtils::MakeMaker';
  requires 'ExtUtils::MakeMaker::CPANfile';
};

on 'test' => sub {
  requires 'Test::More';
};
