version: "3.7"
services:
  head:
    image: uralm1/r2d2-head
    container_name: r2d2-head
    hostname: r2d2-head
    domainname: uwc.local
    networks:
      uwcnet:
        ipv4_address: 10.14.72.5
      default:
    dns:
      - 10.14.0.2
      - 10.14.0.4
    cap_add:
      - NET_ADMIN
    volumes:
      - /srv/r2d2-head/head.conf:/opt/head/head.conf:ro
      - /srv/r2d2-head/r2d2-head-cert.pem:/opt/head/r2d2-head-cert.pem:ro
      - /srv/r2d2-head/r2d2-head-key.pem:/opt/head/r2d2-head-key.pem:ro
      - /srv/r2d2-head/ca.pem:/opt/head/ca.pem:ro
    environment:
      - TZ=Asia/Yekaterinburg
    restart: unless-stopped

  head-cron:
    image: uralm1/r2d2-head
    container_name: r2d2-head-cron
    hostname: r2d2-head-cron
    domainname: uwc.local
    networks:
      uwcnet:
        ipv4_address: 10.14.72.6
      default:
    dns:
      - 10.14.0.2
      - 10.14.0.4
    cap_add:
      - NET_ADMIN
    volumes:
      - /srv/r2d2-head/head.conf:/opt/head/head.conf:ro
      - /srv/r2d2-head/r2d2-head-cert.pem:/opt/head/r2d2-head-cert.pem:ro
      - /srv/r2d2-head/r2d2-head-key.pem:/opt/head/r2d2-head-key.pem:ro
      - /srv/r2d2-head/ca.pem:/opt/head/ca.pem:ro
    environment:
      - TZ=Asia/Yekaterinburg
    command: sh -c "script/check_db_hosts && script/add_route && su -s /usr/bin/perl head script/head cron"
    #command: sh -c "script/check_db_hosts && su -s /usr/bin/perl head script/head cron"
    depends_on:
      - head
    restart: unless-stopped

networks:
  uwcnet:
    external:
      name: uwcnet

