#!/bin/bash

docker run -d --name r2d2-master \
  -h r2d2-master \
  -v /srv/r2d2-master/master.conf:/opt/master/master.conf:ro \
  -v /srv/r2d2-master/r2d2-master-cert.pem:/opt/master/r2d2-master-cert.pem:ro \
  -v /srv/r2d2-master/r2d2-master-key.pem:/opt/master/r2d2-master-key.pem:ro \
  -e TZ=Asia/Yekaterinburg \
  -p 2271:2271 \
  uralm1/r2d2-master
