use Mojo::Base -strict;

use Test::Mojo;
use Test::More;
use Test::Files;
use Mojo::File qw(path);

diag "need some files to test...";
my $fh = undef;
my $testdir = path('/tmp', 'r2d2test')->make_path;
while (<DATA>) {
  last if /^__END__$/;
  if (/^@@ *(\S+)$/) {
    diag "prepare file $1";
    $fh->close if $fh;
    $fh = path($testdir, $1)->open('>');
    next;
  }
  print $fh $_ if $fh;
}
$fh->close if $fh;

my $test_f = path($testdir, 'traf.clients1');
my $t = Test::Mojo->new('Fwsyn', { tc_file => $test_f->to_string,
  tc_path => '/usr/sbin/tc',
  my_profiles => ['plk'],
});
my $j = [
  {id=>11, ip=> '1.2.3.4', mac=>'11:22:33:44:55:66', profile=>'zzz'},
  {id=>1, ip=> '1.2.3.1', profile=>'plk'},
  {id=>2, ip=> '1.2.3.2', mac=>'11:22:33:44:55:66', profile=>'plk', no_dhcp=>1},
  {id=>12, ip=> '1.2.3.5', mac=>'11:22:33:44:55:77', speed_in=>'rate 1Mbit prio 5', speed_out=>'rate 768kbit prio 5', profile=>'plk'},
  {id=>13, ip=> '1.2.3.6', mac=>'11:22:33:44:55:88', speed_out=>'rate 64kbit prio 5', profile=>'plk'},
  {id=>14, ip=> '1.2.3.7', mac=>'11:22:33:44:55:99'},
];
is($t->app->tc_create_full($j), 1, 'tc_create_full1');
compare_ok($test_f, path($testdir, 'result1'), 'compare results 1');

done_testing();

__DATA__
@@ result1
# WARNING: this is autogenerated file, don't run or change it!

# 300 1
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:300 handle 300: pfifo limit 150
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 1.2.3.1 flowid 1:300
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.1 match ip src 10.15.0.1 match ip sport 3128 0xffff flowid 1:300
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:300 handle 300: pfifo limit 120
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 1.2.3.1 flowid 1:300
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.1 match ip src 192.168.12.1 match ip sport 3128 0xffff flowid 1:300

# 301 2
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:301 handle 301: pfifo limit 150
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 1.2.3.2 flowid 1:301
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.2 match ip src 10.15.0.1 match ip sport 3128 0xffff flowid 1:301
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:301 handle 301: pfifo limit 120
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 1.2.3.2 flowid 1:301
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.2 match ip src 192.168.12.1 match ip sport 3128 0xffff flowid 1:301

# 302 12
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:302 htb rate 1Mbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:302 handle 302: pfifo limit 150
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 1.2.3.5 flowid 1:302
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.5 match ip src 10.15.0.1 match ip sport 3128 0xffff flowid 1:302
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:302 htb rate 768kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:302 handle 302: pfifo limit 120
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 1.2.3.5 flowid 1:302
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.5 match ip src 192.168.12.1 match ip sport 3128 0xffff flowid 1:302

# 303 13
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:303 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:303 handle 303: pfifo limit 150
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 1.2.3.6 flowid 1:303
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.6 match ip src 10.15.0.1 match ip sport 3128 0xffff flowid 1:303
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:303 htb rate 64kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:303 handle 303: pfifo limit 120
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 1.2.3.6 flowid 1:303
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 4 u32 match ip dst 1.2.3.6 match ip src 192.168.12.1 match ip sport 3128 0xffff flowid 1:303

__END__
