package Rtsyn::Plugin::Loadclients_impl;
use Mojo::Base 'Mojolicious::Plugin';

use Mojo::File qw(tempfile);
use Mojo::UserAgent;

#use Carp;

sub register {
  my ($self, $app, $args) = @_;
  $args ||= {};

  # build rulefile and load it to iptables (blocking)
  # doesn't log anything to remote log, returns 1-success, dies on error
  $app->helper(load_clients => sub {
    my $self = shift;

    my $prof = $self->config('my_profile');
    my $res = eval {
      my $tx = $self->ua->get($self->config('head_url')."/clients/$prof" => {Accept => 'application/json'});
      $tx->result;
    };
    if (defined $res) {
      if ($res->is_success) {
        if (my $v = $res->json) {

          # create rule-file
          my $rulefile = tempfile;
          my $fh = $rulefile->open('>');
          if (defined $fh) {
            my $client_out_chain = $self->config('client_out_chain');

            # header
            print $fh "# WARNING: this is autogenerated file, don't run or change it!\n\n";
            print $fh "*mangle\n";
            print $fh ":$client_out_chain - [0:0]\n\n";

            # data
            for (@$v) {
              #print $fh "# $_->{id}: $_->{login}\n";
              print $fh "-A $client_out_chain -s $_->{ip} -m comment --comment $_->{id} ".$self->rt_marks($_->{rt})."\n";
            }

            # footer
            print $fh "COMMIT\n";
            $fh->close;

            # load rules with iptables_restore
            # note: iptables_restore still flushes user chains mentioned in file
            if (!$self->system(iptables_restore => "--noflush < $rulefile")) {
              return 1; # success
            } else {
              die "Can't activate iptables configuration";
            }

          } else {
            die "Can't create temporary file: $!";
          }
        } else {
          die 'Clients response json error';
        }
      } else {
        die "Clients request error: ".(($res->is_error) ? $res->body : '');
      }
    } else {
      die "connection to head failed: $@";
    }
  });
}


1;
