#!/bin/sh

#make dist
version=`perl -E 'use lib "lib";use Gwsyn;say $Gwsyn::VERSION'`

rexlib=root@bikini:/var/www/net/rexlib
destdir=$rexlib/lib/Deploy/Owrt/R2d2/files

# source tarball
cp gwsyn-$version.tar.gz gwsyn-latest.tar.gz
filelist=gwsyn-latest.tar.gz

# copy keys
cert_path="../cert"
keys="$cert_path/ca.pem"
for h in gwtest1 gwsev gwkns3
do
  keys="$keys $cert_path/$h-cert.pem $cert_path/$h-key.pem"
done
#echo $keys
filelist="$filelist $keys"

# service scripts
filelist="$filelist support/gwsyn support/gwsyn-minion support/gwsyn-cron"

scp $filelist $destdir

rm gwsyn-latest.tar.gz
