#!/bin/bash

#docker volume create r2d2-ui_public
docker run -d --name r2d2-ui \
  -h r2d2-ui \
  -v /srv/r2d2-ui/ui.conf:/opt/ui/ui.conf:ro \
  -v r2d2-ui_public:/opt/ui/public \
  -e TZ=Asia/Yekaterinburg \
  -p 3000:3000 \
  uralm1/r2d2-ui
