requires 'Mojolicious', '8.50';
requires 'EV';
requires 'Cpanel::JSON::XS', '4.10';
requires 'IO::Socket::SSL', '2.009';
requires 'Net::LDAP', '0.65';
requires 'Net::LDAP::Util';
requires 'MIME::Base64';
requires 'Regexp::Common';
requires 'Time::Piece';
requires 'HTTP::BrowserDetect', '3.23';
requires 'ExtUtils::MakeMaker::CPANfile';

on 'configure' => sub {
  requires 'ExtUtils::MakeMaker';
  requires 'ExtUtils::MakeMaker::CPANfile';
};

on 'test' => sub {
  requires 'Test::More';
};
