version: "3.7"
services:
  proxy:
    image: uralm1/uwc-llng-proxy
    container_name: r2d2-ui-proxy
    hostname: r2d2-ui-proxy
    domainname: uwc.ufanet.ru
    networks:
      uwcnet:
        ipv4_address: 10.14.72.8
      default:
    dns:
      - 10.14.0.2
      - 10.14.0.4
    volumes:
      - /etc/ssl/certs/uwc.ufanet.ru.pem:/etc/ssl/certs/u.pem:ro
      - /etc/ssl/private/uwc.ufanet.ru-key.pem:/etc/ssl/private/u.key:ro
      - public:/opt/ui/public
    environment:
      - TZ=Asia/Yekaterinburg
      - PUBLIC_ROOT=/opt/ui/public
      - PROXY_ADDR=http://r2d2-ui-app:3000/
    links:
      - app:r2d2-ui-app
    restart: unless-stopped

  app:
    image: uralm1/r2d2-ui
    container_name: r2d2-ui
    volumes:
      - /srv/r2d2-ui/ui.conf:/opt/ui/ui.conf:ro
      - public:/opt/ui/public
    environment:
      - TZ=Asia/Yekaterinburg
    links:
      - worker
    restart: unless-stopped

volumes:
  public:

networks:
  uwcnet:
    external:
      name: uwcnet

