use Mojo::Base -strict;

use Test::Mojo;
use Test::More;
use Test::Files;
use Mojo::File qw(path);

diag "need some files to test...";
my $fh = undef;
my $testdir = path('/tmp', 'r2d2test')->make_path;
while (<DATA>) {
  last if /^__END__$/;
  if (/^@@ *(\S+)$/) {
    diag "prepare file $1";
    $fh->close if $fh;
    $fh = path($testdir, $1)->open('>');
    next;
  }
  print $fh $_ if $fh;
}
$fh->close if $fh;


note "common usage";
my $test_f = path($testdir, 'traf.clients1');
my $t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(451), 1, 'tc_delete1 451');
is($t->app->tc_delete(452), 1, 'tc_delete1 452');
is($t->app->tc_delete(452), 0, 'tc_delete1 452 non existent');
is($t->app->tc_delete(450), 1, 'tc_delete1 450');
compare_ok($test_f, path($testdir, 'result1'), 'compare results 1');
undef $t;

note "without newlines";
$test_f = path($testdir, 'traf.clients2');
$t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(450), 1, 'tc_delete2 450');
compare_ok($test_f, path($testdir, 'result2'), 'compare results 2');
undef $t;

note "without rules and newlines";
$test_f = path($testdir, 'traf.clients3');
$t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(450), 1, 'tc_delete3 450');
compare_ok($test_f, path($testdir, 'result3'), 'compare results 3');
undef $t;

note "without rules, with newlines";
$test_f = path($testdir, 'traf.clients4');
$t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(450), 1, 'tc_delete4 450');
compare_ok($test_f, path($testdir, 'result4'), 'compare results 4');
undef $t;

note "intersecting ids: 45 and 450";
$test_f = path($testdir, 'traf.clients5');
$t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(45), 0, 'tc_delete5 45 non existent');
is($t->app->tc_delete(450), 1, 'tc_delete5 450');
compare_ok($test_f, path($testdir, 'result5'), 'compare results 5');
undef $t;

note "duplicate ids, issue warnings";
$test_f = path($testdir, 'traf.clients6');
$t = Test::Mojo->new('Gwsyn', {tc_file => $test_f->to_string, tc_path => '/usr/sbin/tc',
  rlog_local=>1, rlog_remote=>0});
is($t->app->tc_delete(450), 1, 'tc_delete6 450, duplicate ids, issue warnings');
compare_ok($test_f, path($testdir, 'result6'), 'compare results 6');
undef $t;

done_testing();

__DATA__
@@ traf.clients1
# WARNING: this is autogenerated file, don't run or change it!

# 300 450
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 1mbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:300 handle 300: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.23 flowid 1:300
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 2mbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:300 handle 300: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.23 flowid 1:300

# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:301 handle 301: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.24 flowid 1:301
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:301 handle 301: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.24 flowid 1:301

# 302 452
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.25 flowid 1:302
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.25 flowid 1:302

@@ result1
# WARNING: this is autogenerated file, don't run or change it!

@@ traf.clients2
# WARNING: this is autogenerated file, don't run or change it!
# 300 450
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 1mbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:300 handle 300: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.23 flowid 1:300
# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
@@ result2
# WARNING: this is autogenerated file, don't run or change it!
# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
@@ traf.clients3
# WARNING: this is autogenerated file, don't run or change it!
# 300 450
# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5

@@ result3
# WARNING: this is autogenerated file, don't run or change it!
# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5

@@ traf.clients4
# WARNING: this is autogenerated file, don't run or change it!
# 300 450

# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
@@ result4
# WARNING: this is autogenerated file, don't run or change it!
# 301 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
@@ traf.clients5
# WARNING: this is autogenerated file, don't run or change it!
# 300 450
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 1mbit prio 5
@@ result5
# WARNING: this is autogenerated file, don't run or change it!
@@ traf.clients6
# WARNING: this is autogenerated file, don't run or change it!

# 300 450
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 1mbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:300 handle 300: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.23 flowid 1:300
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:300 htb quantum 6400 rate 2mbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:300 handle 300: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.23 flowid 1:300

# 301 450
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:301 handle 301: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.24 flowid 1:301
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:301 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:301 handle 301: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.24 flowid 1:301

# 302 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.25 flowid 1:302
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.25 flowid 1:302

@@ result6
# WARNING: this is autogenerated file, don't run or change it!

# 302 451
/usr/sbin/tc class add dev $INTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $INTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $INTR_IF parent 1:0 protocol ip pref 10 u32 match ip dst 192.168.34.25 flowid 1:302
/usr/sbin/tc class add dev $EXTR_IF parent 1:10 classid 1:302 htb quantum 6400 rate 256kbit prio 5
/usr/sbin/tc qdisc add dev $EXTR_IF parent 1:302 handle 302: pfifo limit 100
/usr/sbin/tc filter add dev $EXTR_IF parent 1:0 protocol ip pref 10 u32 match ip src 192.168.34.25 flowid 1:302

__END__
