#!/bin/sh

#make dist
version=`perl -E 'use lib "lib";use Fwsyn;say $Fwsyn::VERSION'`
version_ljq=`perl -E 'use lib "../ljq/lib";use Ljq;say $Ljq::VERSION'`

rexlib=root@bikini:/var/www/net/rexlib
destdir=$rexlib/lib/Deploy/Fw/R2d2/files

# check files
[ ! -f ../ljq/ljq-$version_ljq.tar.gz ] && echo "ERROR: ljq source tarball is not found! Run make dist first." && exit 1
[ ! -f fwsyn-$version.tar.gz ] && echo "ERROR: fwsyn source tarball is not found! Run make dist first." && exit 1

# source tarballs
cp fwsyn-$version.tar.gz fwsyn-latest.tar.gz
cp ../ljq/ljq-$version_ljq.tar.gz ljq-latest.tar.gz
filelist="fwsyn-latest.tar.gz ljq-latest.tar.gz"

# copy keys
cert_path="../cert"
keys="$cert_path/ca.pem"
for h in fw
do
  keys="$keys $cert_path/$h-cert.pem $cert_path/$h-key.pem"
done
#echo $keys
filelist="$filelist $keys"

# service scripts
filelist="$filelist support/rc.fwsyn support/fwsyn.logrotate"

scp $filelist $destdir

rm fwsyn-latest.tar.gz ljq-latest.tar.gz
