#!/bin/sh

# verify = SSL_VERIFY_PEER (0x01) & SSL_VERIFY_FAIL_IF_NO_PEER_CERT (0x02)
SP=`perl -MMojolicious::Plugin::Config -E 'my $c=Mojolicious::Plugin::Config->new->load("fwsyn.conf");say "?cert=$c->{local_cert}&key=$c->{local_key}&ca=$c->{ca}&verify=0x03"'`

MOJO_LISTEN="https://*:2275$SP"
#MOJO_LISTEN='http://*:2275'

#echo $MOJO_LISTEN
export MOJO_LISTEN

morbo script/fwsyn -l $MOJO_LISTEN
#script/fwsyn daemon -l $MOJO_LISTEN
#script/fwsyn prefork -l $MOJO_LISTEN
